version: "3.9"

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cosette_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cosette-net

  # Redis 缓存
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - cosette-net

  # NestJS 应用
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: server
    image: server:latest
    restart: always
    ports:
      - "3000:3000"
    networks:
      - cosette-net
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env

  # Nginx 反向代理
  nginx:
    image: nginx:stable-alpine
    container_name: proxy
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    privileged: true
    depends_on:
      - server
    networks:
      - cosette-net

networks:
  cosette-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
