version: "3.9"

services:
  
  servers:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - cosette-net
    volumes:
      - upload:/upload
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env

  mysql:
    container_name: mysql
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Y349^&84dk4Hwe
      - MYSQL_DATABASE=cosette-database
    networks:
      - cosette-net
    volumes:
      - ./prisma/data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - cosette-net
    volumes:
      - redis:/data

networks:
  cosette-net:
    driver: bridge

volumes:
  mysql:
  redis:
  upload:
